# This workflow performs the following:
# - Database configuration
# - Provisioning Azure Services  
# - Create the spring-petclinic-AKS App on Docker
# - Create an Azure Container Registry 
# - Push your app to the container registry
# - Create a Kubernetes Cluster on AKS 
# - Deploy the image to your Kubernetes cluster
# - Verify your container image
#
# Secrets required to be in place:
# - AZURE_CREDENTIALS

name: Build and Deploy Application
env:
  # This is the global resource prefix for this deployment
  # Use lower case letters and numbers only
  DEPLOYMENT_NAME: "petclinicaks"

  # Azure region to which the resources will be deployed
  DEPLOYMENT_REGION: "eastus"

on:
  # Triggers the workflow on push events on the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '*.png'

  # We also want to be able to run this manually from Github
  workflow_dispatch:
jobs:
  build-and-deploy:
     runs-on: ubuntu-latest
     steps:

     - name: 'Checkout GitHub Action'
       uses: actions/checkout@main
          
     - name: 'Login via Azure CLI'
       uses: azure/login@v1
       with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
     - name: Azure CLI -Deploy Bicep Files
       uses: Azure/CLI@v1
       with:
        inlineScript: |
          #!/bin/bash
          az deployment sub create --template-file ./infra/aks-bicep/main.bicep --location eastus
   
      # Build Java Application
     - name: Build Java Application
       uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
          java-version: '11'
          distribution: 'adopt'
     - name: Build with Maven, compile and build the Docker image
       run: |
        mvn spring-boot:build-image

     # Azure Powershell Cli - ACR Login
     - name: Azure Powershell Cli - ACR Login
       uses: azure/powershell@v1
       with:
        inlineScript: |
         #!/bin/bash
         az acr login --name petclinicaksacraz
        azPSVersion: "latest"
    
     # Azure Powershell Cli - Tag and Push to ACR
     - name: Azure Powershell Cli - Tag and Push to ACR
       uses: azure/powershell@v1 
       with:
        inlineScript: |
         #!/bin/bash
         docker tag docker.io/library/spring-petclinic:2.7.0-SNAPSHOT petclinicaksacraz.azurecr.io/petclinic
         docker push petclinicaksacraz.azurecr.io/petclinic
        azPSVersion: "latest" 
       
     # Azure Powershell Cli - Update AKS Cluster and Integrate ACR
     - name: Azure Powershell Cli - Update AKS Cluster and Integrate ACR
       uses: azure/powershell@v1
       with:
        inlineScript: |
         #!/bin/bash
         az aks create --resource-group=petclinicaks-rg --name=aks-cluster --attach-acr petclinicaksacraz --dns-name-prefix=petclinicaks --generate-ssh-keys
         az aks get-credentials --resource-group=petclinicaks-rg --name=aks-cluster
        azPSVersion: "latest"
      
    # Azure Powershell Cli - Deploy image to AKS Cluster with kubectl kubectl run petclinicjaks --image=petclinicaksacraz.azurecr.io/petclinic:latest
     - name: Azure Powershell Cli - Deploy image to AKS Cluster with kubectl
       uses: azure/powershell@v1
       with:
        inlineScript: | 
         kubectl run petclinicaks --image=petclinicaksacraz.azurecr.io/petclinic
         kubectl expose pod petclinicaks --type=LoadBalancer --port=80 --target-port=8080
        azPSVersion: "latest"

    # Azure Powershell Cli - ACR Login
     - name: Azure Powershell Cli - ACR Login
       uses: azure/powershell@v1
       with:
        inlineScript: |
         #!/bin/bash
         az acr login --name petclinicaksacraz
         az aks get-credentials --resource-group=petclinicaks-rg --name=aks-cluster
        azPSVersion: "latest"
    
     # Azure Powershell Cli - Get deployment IP Address 
     - name: Azure Powershell Cli - Get deployment IP Address 
       uses: azure/powershell@v1
       with:
        inlineScript: | 
         kubectl get service petclinicaks -o=jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}'
         kubectl get pods -A
         kubectl get service petclinicaks
         kubectl describe service petclinicaks
        azPSVersion: "latest"