# This workflow performs the following:
# - Database configuration
# - Provisioning Azure Services  
# - Create the spring-petclinic-AKS App on Docker
# - Create an Azure Container Registry 
# - Push your app to the container registry
# - Create a Kubernetes Cluster on AKS 
# - Deploy the image to your Kubernetes cluster
# - Verify your container image
#
# Secrets required to be in place:
# - AZURE_CREDENTIALS

name: Build and Deploy Application
env:
  # This is the global resource prefix for this deployment
  # Use lower case letters and numbers only
  DEPLOYMENT_NAME: "petclinicaks"

  # Azure region to which the resources will be deployed
  DEPLOYMENT_REGION: "eastus"

on:
  # Triggers the workflow on push events on the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - '*.png'

  # We also want to be able to run this manually from Github
  workflow_dispatch:
jobs:
  build-and-deploy:
     runs-on: ubuntu-latest
     steps:

     - name: 'Checkout GitHub Action'
       uses: actions/checkout@main
          
     - name: 'Login via Azure CLI'
       uses: azure/login@v1
       with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
     - name: Azure CLI -Deploy Bicep Files
       uses: Azure/CLI@v1
       with:
        inlineScript: |
          #!/bin/bash
          az deployment sub create --template-file ./infra/aks-bicep/main.bicep --parameters ./infra/aks-bicep/parameters.json --location eastus
   
      # Build Java Application
     - name: Build Java Application
       uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
          java-version: '11'
          distribution: 'adopt'
     - name: Build with Maven, compile and build the Docker image
       run: |
        mvn spring-boot:build-image

     # Azure Powershell Cli - ACR Login
     - name: Azure Powershell Cli - ACR Login
       uses: azure/powershell@v1
       with:
        inlineScript: |
         #!/bin/bash
         az acr login --name petclinicaksacrazure.azurecr.io
        azPSVersion: "latest"
    
     # Azure Powershell Cli - Tag and Push to ACR
     - name: Azure Powershell Cli - Tag and Push to ACR
       uses: azure/powershell@v1 
       with:
        inlineScript: |
         #!/bin/bash
         docker tag docker.io/library/spring-petclinic:2.7.0-SNAPSHOT petclinicaksacrazure.azurecr.io/petclinic
         docker push petclinicaksacrazure.azurecr.io/petclinic
        azPSVersion: "latest" 
       
     # Azure Powershell Cli - update RG & Cluster Credentials 
     - name: Azure Powershell Cli - update RG & Cluster Credentials 
       uses: azure/powershell@v1
       with:
        inlineScript: |
         #!/bin/bash
         az aks update -g petclinicaks-rg -n aks-cluster --attach-acr petclinicaksacrazure.azurecr.io
        azPSVersion: "latest"
      
    # Azure Powershell Cli - Deploy image to AKS Cluster with kubectl
     - name: Azure Powershell Cli - Deploy image to AKS Cluster with kubectl
       uses: azure/powershell@v1
       with:
        inlineScript: | 
         #!/bin/bash
         kubectl run aks-cluster --image=petclinicaksacrazure.azurecr.io/petclinic:latest
         kubectl expose pod aks-cluster --type=LoadBalancer --port=80 --target-port=8080
         kubectl get services -o=jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}'
        azPSVersion: "latest"
